name: "klaviyo-fivetran-to-daton"
version: "1.0.0"
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]
profile: "klaviyo_daton_package"

vars:
  raw_database: "solutionsdw" #equivalent to project_id in BigQuery
  raw_schema:  "edm_test" #equivalent to dataset in BigQuery

  # Klaviyo raw table patterns as variables
  klaviyo_event_table_pattern: "%klaviyo%events"
  klaviyo_flow_action_table_pattern: "%klaviyo%flow_actions"
  klaviyo_flow_message_table_pattern: "%klaviyo%flow_messages"
  klaviyo_flow_action_tracking_utm_param_table_pattern: "%klaviyo%flow_actions"
  klaviyo_campaign_tracking_utm_param_table_pattern: "%klaviyo%campaigns"
  klaviyo_person_table_pattern: "%klaviyo%profiles"
  klaviyo_segment_table_pattern: "%klaviyo%segments"
  klaviyo_campaign_list_table_pattern: "%klaviyo%campaigns"
  klaviyo_metric_table_pattern: "%klaviyo%metrics"
  klaviyo_flow_table_pattern: "%klaviyo%flows"
  klaviyo_campaign_table_pattern: "%klaviyo%campaigns"
  klaviyo_campaign_message_table_pattern: "%tc_klaviyo%campaign_metadata"
  klaviyo_campaign_message_send_time_table_pattern: "%klaviyo%campaigns"

  # Klaviyo model variables
  klaviyo_event: true
  klaviyo_flow_action: true
  klaviyo_flow_message: true
  klaviyo_flow_action_tracking_utm_param: true
  klaviyo_campaign_tracking_utm_param: true
  klaviyo_person: true
  klaviyo_segment: true
  klaviyo_campaign_list: true
  klaviyo_metric: true
  klaviyo_flow: true
  klaviyo_campaign: true
  klaviyo_campaign_message: true
  klaviyo_campaign_message_send_time: true




# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  klaviyo_daton_package:
    Staging:
      +schema: staging


